### ISSUE TITLE
Snowpark method for airflow-extensions is broken.

### ISSUE THREAD

**Issue by abhishekbhakat** [astronomer/astro-provider-venv#17]
**Describe the bug**

This method was using `python3.8:slim` image which is based on bookworm debian. Recently the new image for python has bumped the glibc version to 2.36. We can check that by `ldd --version`. Whereas our base runtime images are built on debian11 which only has glibc version 2.31.

```
 => ERROR [stage-0 13/17] RUN /usr/local/bin/python3.8 -m venv /home/astro/.venv/snowpark                                                    0.1s
------
 > [stage-0 13/17] RUN /usr/local/bin/python3.8 -m venv /home/astro/.venv/snowpark:
#0 0.115 + /usr/local/bin/python3.8 -m venv /home/astro/.venv/snowpark
#0 0.116 /usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/python3.8)
#0 0.116 /usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)
#0 0.116 /usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)
#0 0.116 /usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)
#0 0.116 /usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)
------
Dockerfile:31
--------------------
  29 |     RUN mkdir -p /home/astro/.venv/snowpark
  30 |     COPY nre_req.txt /home/astro/.venv/snowpark/requirements.txt
  31 | >>> RUN /usr/local/bin/python3.8 -m venv /home/astro/.venv/snowpark
  32 |     ENV ASTRO_PYENV_snowpark /home/astro/.venv/snowpark/bin/python
  33 |     RUN --mount=type=cache,target=/home/astro/.cache/pip /home/astro/.venv/snowpark/bin/pip --cache-dir=/home/astro/.cache/pip install -r /home/astro/.venv/snowpark/requirements.txt
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -e -u -x -c /usr/local/bin/python3.8 -m venv /home/astro/.venv/snowpark" did not complete successfully: exit code: 1
```

**What CLI Version did you experience this bug?**

Version 1.16.1. But Cli version doesn't matter in this scenario.

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [x] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

Follow the [documentation](https://docs.astronomer.io/learn/external-python-operator#step-2-configure-your-astro-project)

**Comment by ashb** [comment]
Hmmm, so switching it to `3.8-slim-buster` would work -- except for when we upgrade the runtime images to use Bookworm (which we likely will soon. I'll chat with the team and see if that would be a Runtime 9.0 or if we'll do it in-stream for the existing releases etc.)

**Comment by abhishekbhakat** [comment]
Would it not be possible to automate selection of tags by checking `/etc/os-release` of base image on fly ?

**Comment by ashb** [comment]
@abhishekbhakat Not trivially -- at the time we build the dockerfile instructions we don't actually have access to the image or any of the files in it -- it's just how docker builders work.
